#!/bin/sh

# 挂载虚拟文件系统
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mount -t tmpfs none /tmp

# 设置主机名
hostname MyCustomLinux

# 启动 shell
echo "Welcome to My Custom Linux System!"
echo "Kernel: $(uname -r)"
echo "Architecture: $(uname -m)"

# 如果不需要交互式shell，可以启动其他服务
# /etc/init.d/ssh start

exec /bin/sh
